name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: lateidev
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=C0C0C0&color_dots=111111,333333,666666,999999,C0C0C0
            dist/github-contribution-grid-snake-dark.svg?color_snake=FFFFFF&color_dots=111111,333333,666666,999999,C0C0C0

      - name: Push snake files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
